### ISSUE TITLE
PA Review: User Auth

### ISSUE THREAD

**Issue by eaconway** [eaconway/Airbnb-Clone#2]
I DID THE THINGS

**Comment by s-pangburn** [comment]
- [x] Your login form needs more padding on the sides, it's too close to the edge! Try to get the spacing as identical to AirBnB as possible, they should be straight lines down both sides for inputs, the title, buttons, links, everything.
- [x] I would try to find a more appealing place for the errors to show up, preferably centered. Right now, showing up awkwardly spaced above the title of the modal (and under the X) doesn't look too professional.
- [x] `Don't have an account?` Sign up should all be equal font and size, and the alignment needs to be better.
- [x] Errors should clear when switching between forms
- [x] Don't include the line about marketing promotions
- [x] Errors don't show up for the sign up form (log in works fine)
- [x] Remove "Forgot Password?"
- [x] Title would probably look better centered, and not so far down from the X, looks a little strange.
- [x] If you want to be able to Show Password, you should have it able to toggle (Hide Password) as well since someone might hit it by mistake.
- [x] When attempting to sign up, I get this error:
![screen shot 2018-10-16 at 10 59 57 am](https://user-images.githubusercontent.com/8031316/47037025-ac0e7a00-d132-11e8-9ab4-09c303e3f200.png)
- [x] Demo login doesn't work without seeds
- [x] I can't test logout because I can't login lol

Let me know once you've addressed this feedback and I'll take another look!

**Comment by eaconway** [comment]
Alright, thanks for the feedback. I'm not sure what happened to my styling, but it looks like some of the functionality was definitely lost as I've been messing with other pieces. Apologies for the incomplete feature. It should be fixed now 👍. I'm uploading to Heroku now.

**Comment by s-pangburn** [comment]
- [x] Upon login, "Become a Host" in the nav is text-aligned left for some reason? It looks really awkward, haha.
- [x] Logout should _probably_ underline or something on hover the way everything else does? Unless AirBnB doesn't do it that way for some reason, idk.
- [x] Demo should be centered, or even better, it should be a button just like Login. I think that would just look better 👍 
- [x] Interestingly, pressing enter on your login form doesn't submit, it shows the password instead, which, if this were an actual website, would be horrifying LOL
   - EDIT: Same with signup

Otherwise, it's looking really polished now! Great job EJ! 🙂

**Comment by eaconway** [comment]
Confirming these are all checked off! Thanks

**Comment by s-pangburn** [comment]
Confirming that it works! :+1: Awesome job EJ! I'll mark this MVP complete.
